services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token eyJhIjoiZTcxMzRjZWI0OTRlZGNjOWYxNTM2YWMwYTc3MDc1MjQiLCJ0IjoiNjdjMjk0MzMtM2RmOS00MWUzLTljMzQtNTMxZGYyM2U4YTc1IiwicyI6Ik1UYzNOamd4TlRFdE16VTNOQzAwTkdVNUxUaG1PV1l0TWpBelpHVmhNemN6WldZeSJ9
    restart: always
    networks:
      - zelo-network
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - WEBHOOK_URL=https://n8n.zelo-server.com.br
    ports:
      - 5678:5678
    networks:
      - zelo-network
    volumes:
      - C:\Users\Joao\Documents\Projetos\zelo:/zelo-git
      - n8n_data:/home/node/.n8n
  server:
    build: zelo-core
    user: "0"
    container_name: server
    restart: always
    environment:
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - 80:80
    networks:
      - zelo-network
    volumes:
      - C:\Users\Joao\Documents\Projetos\zelo\zelo-core:/app
volumes:
  zelo-data:
  n8n_data:

networks:
  zelo-network:
    driver: bridge