services:
  server:
    build: zelo-core
    user: "0"
    container_name: server
    restart: always
    environment:
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - 80:80
      - 443:443
    networks:
      - zelo-network
  banco:
    image: mysql:5.5
    container_name: banco
    restart: always
    environment:
      - MYSQL_DATABASE=Zelo
      - MYSQL_ROOT_PASSWORD=zeloroot
    ports:
      - 3306:3306
    volumes:
      - zelo-data:/var/lib/mysql
    networks:
      - zelo-network

volumes:
  zelo-data:
  n8n_data:


networks:
  zelo-network:
    driver: bridge
