services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64
    container_name: banco
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=zeloroot
    ports:
      - 3306:3306
    volumes:
      - zelo-data:/var/lib/mysql
    networks:
      - zelo-network
  cloudflared:
    image: cloudflare/cloudflared
    platform: linux/arm64
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token eyJhIjoiZTcxMzRjZWI0OTRlZGNjOWYxNTM2YWMwYTc3MDc1MjQiLCJ0IjoiNjdjMjk0MzMtM2RmOS00MWUzLTljMzQtNTMxZGYyM2U4YTc1IiwicyI6Ik1UYzNOamd4TlRFdE16VTNOQzAwTkdVNUxUaG1PV1l0TWpBelpHVmhNemN6WldZeSJ9
    restart: always
    networks:
      - zelo-network
  n8n:
    image: n8nio/n8n
    platform: linux/arm64
    container_name: n8n
    restart: always
    environment:
      - WEBHOOK_URL=https://n8n.zelo-server.com.br
    ports:
      - 5678:5678
    networks:
      - zelo-network
    volumes:
      - /home/admin/projetos/zelo/zelo:/zelo-git
      - n8n_data:/home/node/.n8n
  server:
    build: zelo-core
    platform: linux/arm64
    container_name: server
    restart: always
    environment:
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - 80:80
    networks:
      - zelo-network
    volumes:
      - /home/admin/projetos/zelo/zelo/zelo-core:/app
volumes:
  zelo-data:
  n8n_data:

networks:
  zelo-network:
    driver: bridge