name: Deploy pra AWS

on:
    push:
        branches:
            - main
        paths:
            - 'zelo-core/**'

    pull_request:
        branches:
            - main
        paths:
            - 'zelo-core/**'
    
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout no repositório
              uses: actions/checkout@v3

            - name: Configura o .NET
              uses: actions/setup-dotnet@v3
              with:
                    dotnet-version: '6.0.x'

            - name: Configura as credências da AWS
              uses: aws-actions/configure-aws-credentials@v3
              with: 
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: sa-east-1
                    
            - name: Faz o build da aplicação .NET
              run: |
                cd zelo-core
                dotnet restore
                dotnet publish -c Release -o ./publish

            - name: Empacota o arquivo
              run: |
                cd zelo-core
                zip -r app.zip ./publish

            - name: Upload and deploy to Elastic Beanstalk
              run: |
                cd zelo-core
                aws s3 cp app.zip s3://elasticbeanstalk-sa-east-1-872515282645/app.zip
                aws elasticbeanstalk create-application-version --application-name "Zelo" --version-label v1.0 --source-bundle S3Bucket="elasticbeanstalk-sa-east-1-872515282645",S3Key="app.zip"
                aws elasticbeanstalk update-environment --environment-name "Zelo-env" --version-label v1.0
                